### ISSUE TITLE
Bug in scglrTheme function

### ISSUE THREAD

**Issue by tiemor75** [SCnext/SCGLR#5]
**Describe the bug**
Not updating linear predictors in Theme

In the loop for(t in seq(1, length(out))){ ...} line 373, did not work because "out" is a list of length 1 containing a list of themes. Then length(out) is always equal to one.

solutions : 
a/ change length(out) by sum(H>0)
or
b/ modify out object itself

**Comment by billy34** [comment]
why not change change `length(out)` by `length(out$themes)` ?
